services:
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/changeme123
      - SERVICE_URL_BROWSER=http://neo4j.globalimex.online:7474
      - SERVICE_URL_BOLT=http://bolt.globalimex.online:7687

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
